url = 'your_domain/select/logsql/query'
topic = 'prod*' # prod, test, dev...
caller = '*'

start = '2020-01-01T00:00:00+08:00'
end = '2020-01-02T00:00:00+08:00'
limit = 1000

query = '_msg:"demo" name:"leslie"'

fileds = ['_time', '_msg', 'caller', '*']

[stream]
    service = 'victoria'

