url = 'your_domain/select/logsql/query'
topic = 'prod*' # prod, test, dev...
caller = '*'

last_duration = '5m' # 5m, 1h, 1d...
start = '2020-01-01T00:00:00+08:00'
end = '2020-01-02T00:00:00+08:00'
limit = 1000
sort = 'desc' # asc, desc

ignore_ori_query = false # default false, if true, will ignore origin query in logsql

query = '_msg:"demo" name:"leslie"'
Level = '*'

fileds = ['_time', '_msg', 'caller', '*']

custom_pipes = ['top 7 by (_stream)', 'sort by (_time) asc'] # custom_pipes, and it's up to you

[stream]
    name = 'hello_victoria'
    age = 18
    # other custom fields...
